/* 
 * $Id: x11bitmp.c,v 1.6 2009/01/06 04:54:48 hito Exp $
 * 
 * This file is part of "Ngraph for X11".
 * 
 * Copyright (C) 2002, Satoshi ISHIZAKA. isizaka@msa.biglobe.ne.jp
 * 
 * "Ngraph for X11" is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * "Ngraph for X11" is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 * 
 */

#define ICON_WIDTH 48
#define ICON_HEIGHT 48

#include "gtk_common.h"

const gchar *Icon_xpm[] = {
  "48 48 11 1",
  ". c #000000",
  "# c #0000ff",
  "a c None",
  "b c #00ffff",
  "c c #808000",
  "d c #808080",
  "e c #c0c0c0",
  "f c #ff0000",
  "g c #ffff00",
  "h c #ffffff",
  "i c #008080",
  /* pixels */
  "aaaaaaaaaaaaaaaaaaaaaaaadddaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaaaaaddhhhdaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaaaddhhhhhhdaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaddhhhhhhhhhdaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaddhhhhhhhhhhhhdaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaddhhhhhhhhhhhhhhhdaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaddhhhhhhhhhhhhhhhhhhdaaaaaaaaaaaaaaa",
  "aaaaaaaaaaddhhhhhhhh##hhhhhffhhhhdaaaaaaaaaaaaaa",
  "aaaaaaaaddhhhhhhhhh#bb#hhhffhhhhhhdaaaaaaaaaaaaa",
  "aaaaaaddhhhhhhhhhhh#bb#hhffhhhhhhhhdaaaaaaaaaaaa",
  "aaaaddhhhhhhhhhhhhhh##hhffhhhhhhhhhhdaaaaaaaaaaa",
  "aaddhhhhhhhhhhhhhhhhhhhffhh##hhhhhhhhdaaaaaaaaaa",
  "adhhhhhhhh##hhhh##hhhhffhh#bb#hhhhhhhhdaaaaaaaaa",
  "addhhhhhh#bb#hh#bb#hhffhhh#bb#hhhhhhhhhdaaaaaaaa",
  ".eedhhhhh#bb#hh#bb#hffhhhhh##hhhhhhhhhhhdaaaaaaa",
  ".eeedhhhhh##hhhh##hffhhhhhhhhhhhhhhhhhhhhdaaaaaa",
  ".eeeedh.hhhhhhhhhhffhhhhhhhhhhhhhhhhhhhhhhdaaaaa",
  ".eeeeed..h.hhhhhhffhhhhhhhhhhhhhh.hhhh..hhhdaaaa",
  ".eeeeedh..hhhhhhffh##hhhhhhhhhhhhh.h..hhhhhhdaaa",
  ".eeeeed.h..hhhhffh#bb#hhhhhhhhhhhh..hhhhhhhhhdaa",
  ".eeeedhhhh..h.ffhh#bb#hhhhh.hhhh..hh.hhhhhhhhhda",
  ".eeedhhhhhh..ffhhhh##hhhhhhh.h..hhhhhhhhhhhhhhhd",
  ".eedhhhhhh.h..hhhhhhhhhhhhhh..hhhhhhhhhhhhhhhhhh",
  ".edhhhhhhhhff..h.hhhh.hhhh..ee.eeeeeeeeeeeeehhhh",
  ".dhhhhhhhhffhh..hhhhhh.h..hheeeeeeeeeeeeeeeehhhh",
  ".dhhhhhhhffhh.h..hhhhh..hhhheeeeeeeeeeeeeeeehhhh",
  "..dhhhhhffhhhhhh..hh..hh.hhheeeccccccccccccccchh",
  "a..dhhhffhhhhhhhh...hhhhhhhheeecgggggggggggggggh",
  "aa..dhhhhhhhhhhh....hhhhhhhheeecgggggggggggggggd",
  "aaa..dhhhhhhhh..hhh..hhhhhhheeecgiiiiiiiiiiiiiga",
  "aaaa..dhhhhh..hhhhhh..h.hhhheeecgiibiibiibiibiga",
  "aaaaa..dhhhhhhhhhhhhh..hhhhheeecgiibiibiibiibiga",
  "aaaaaa..dhhhhhhhhhhh.h..hhhheeecgiiiiiiiiiiiiiga",
  "aaaaaaa..dhhhhhhhhhhhhh..hhheeecggggggggggggggga",
  "aaaaaaaa..dhhhhhhhhhhhhhhhhheeecggggggggggggggga",
  "bbbbaaaaa..dbbbbhhhhhhhhhhhheeecggg##gg##gg##gga",
  "bbbbbaaaaa..bbbbhhhhhhhhhhhheedcgg.##g.##g.##gga",
  "bbbbbbaaaaa.bbbbhhhhhhhhhhhhdd.cgg..gg..gg..ggga",
  "bbbbbbbaaaaabbbbhhhhhhhhhhdd...cggggggggggggggga",
  "bbbbbbbbaaaabbbbhhhhhhhhdd.....cggg##gg##gg##gga",
  "bbbbbbbbbaaabbbbdhhhhhdd...a...cgg.##g.##g.##gga",
  "bbbbabbbbbaabbbb.dhhdd...aaa...cgg..gg..gg..ggga",
  "bbbbaabbbbbabbbb..dd...aaaaa...cggggggggggggggga",
  "bbbbaaabbbbbbbbba....aaaaaaaaaacggg##gg##gg##gga",
  "bbbbaaaabbbbbbbbaa.aaaaaaaaaaaacgg.##g.##g.##gga",
  "bbbbaaaaabbbbbbbaaaaaaaaaaaaaaacgg..gg..gg..ggga",
  "bbbbaaaaaabbbbbbaaaaaaaaaaaaaaaaggggggggggggggga",
  "bbbbaaaaaaabbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
};

const gchar *Icon_xpm_64[] = { 
  "64 64 11 1",
  ". c #000000",
  "# c #0000ff",
  "a c None",
  "b c #008080",
  "c c #00ffff",
  "d c #808000",
  "e c #808080",
  "f c #c0c0c0",
  "g c #ff0000",
  "h c #ffff00",
  "i c #ffffff",
  /* pixels */
  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeiieeaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeiiiiieeaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaaaaaaaaaeeeiiiiiiiieeaaaaaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaaaaaaaeeeiiiiiiiiiiieeaaaaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaaaaaeeeiiiiiiiiiiiiiieeaaaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaaaeeeiiiiiiiiiiiiiiiiieeaaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaaaeeeiiiiiiiiiiiiiiiiiiiieeaaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaaaeeeiiiiiiiiiiiiiiiiiiiiiiieeaaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaaaeeeiiiiiiiiiiiiiiiiiiiiiiiiiieeaaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaaaeeeiiiiiiiiiii##iiiiiiiiiiiiiiiieeaaaaaaaaaaaaaaaaaa",
  "aaaaaaaaaaeeeiiiiiiiiiiii#cc#iiiiiiiiiiiiiiiieeaaaaaaaaaaaaaaaaa",
  "aaaaaaaaeeeiiiiiiiiiiiiii#cc#iiiiiggiiiiiiiiiieeaaaaaaaaaaaaaaaa",
  "aaaaaaeeeiiiiiiiiiiiiiiiii##iiiiiggiiiiiiiiiiiieeaaaaaaaaaaaaaaa",
  "aaaaeeeiiiiiiiiiiiiiiiiiiiiiiiiiggiiiiiiiiiiiiiieeaaaaaaaaaaaaaa",
  "aaeeeiiiiiiiiiiiiiiiiiiiiiiiiiiggiii##iiiiiiiiiiieeaaaaaaaaaaaaa",
  "aeeiiiiiiiiiii##iiiiii##iiiiiiggiii#cc#iiiiiiiiiiieeaaaaaaaaaaaa",
  "aeeiiiiiiiiii#cc#iiii#cc#iiiiggiiii#cc#iiiiiiiiiiiieeaaaaaaaaaaa",
  ".eeeiiiiiiiii#cc#iiii#cc#iiiggiiiiii##iiiiiiiiiiiiiieeaaaaaaaaaa",
  ".efeeiiiiiiiii##iiiiii##iiiggiiiiiiiiiiiiiiiiiiiiiiiieeaaaaaaaaa",
  ".effeeiiiiiiiiiiiiiiiiiiiiggiiiiiiiiiiiiiiiiiiiiiiiiiieeaaaaaaaa",
  ".efffeeiiiiiiiiiiiiiiiiiiggiiiiiiiiiiiiiiiiiiiiiiiiiiiieeaaaaaaa",
  ".effffeei..iiiiiiiiiiiiiggiiiiiiiiiiiiiiiiiiiiii.iiiiiiieeaaaaaa",
  ".efffffeei..i.iiiiiiiiiggiiiiiiiiiiiiiiiiiiiiiiii...iiiiieeaaaaa",
  ".effffffeei..iiiiiiiiiggiiiiiiiiiiiiiiiiiiiiiiii...iiiiiiieeaaaa",
  ".effffffee.i..iiiiiiiggiii##iiiiiiiiiiiiii.iii...ii.iiiiiiieeaaa",
  ".efffffeeiiii..i.iiiggiii#cc#iiiiiiiiiiiiii....iiiiiiiiiiiiieeaa",
  ".effffeeiiiiii..iiiggiiii#cc#iiiiiiiiiiiii...iiiiiiiiiiiiiiiieea",
  ".efffeeiiiiii.i..iggiiiiii##iiiiiiii.iii...ii.iiiiiiiiiiiiiiiiee",
  ".effeeiiiiiiiiii..g.iiiiiiiiiiiiiiiif....fffffffffffffffffffiiie",
  ".efeeiiiiiiiiiiig..iiiiiiiiiiiiiiiii...fffffffffffffffffffffiiii",
  ".eeeiiiiiiiiiiig.i..iiiiiiiiii.iii...ff.ffffffffffffffffffffiiii",
  ".eeiiiiiiiiiiiggiii..i.iiiiiiii....iffffffffffffffffffffffffiiii",
  ".eiiiiiiiiiiiggiiiii..iiiiiiii...iiiffffffffffffffffffffffffiiii",
  ".eeiiiiiiiiiggiiiii.i..iiiii...ii.iiffffffffffffffffffffffffiiii",
  "..eeiiiiiiiggiiiiiiiii..ii...iiiiiiiffffffddddddddddddddddddddii",
  "a..eeiiiiiggiiiiiiiiiii....iiiiiiiiiffffffdddddddddddddddddddddi",
  "aa..eeiiiigiiiiiiiiiii....iiiiiiiiiiffffffddhhhhhhhhhhhhhhhhhhhh",
  "aaa..eeiiiiiiiii.iii...ii..i.iiiiiiiffffffddhhhhhhhhhhhhhhhhhhhh",
  "aaaa..eeiiiiiiiii....iiiii..iiiiiiiiffffffddhhbbbbbbbbbbbbbbbbhh",
  "aaaaa..eeiiiiiii...iiiiii.i..iiiiiiiffffffddhhbbcbbcbbcbbcbbcbhh",
  "aaaaaa..eeiiiii..ii.iiiiiiii..i.iiiiffffffddhhbbbbbbbbbbbbbbbbhh",
  "aaaaaaa..eeiiiiiiiiiiiiiiiiii..iiiiiffffffddhhbbcbbcbbcbbcbbcbhh",
  "aaaaaaaa..eeiiiiiiiiiiiiiiii.i..iiiiffffffddhhbbbbbbbbbbbbbbbbhh",
  "aaaaaaaaa..eeiiiiiiiiiiiiiiiiii.iiiiffffffddhhhhhhhhhhhhhhhhhhhh",
  "aaaaaaaaaa..eeiiiiiiiiiiiiiiiiiiiiiiffffffddhhhhhhhhhhhhhhhhhhhh",
  "aaaaaaaaaaa..eeiiiiiiiiiiiiiiiiiiiiiffffffddhhh##hhhh##hhhh##hhh",
  "aaaaaaaaaaaa..eeiiiiiiiiiiiiiiiiiiiiffffffddhh.###hh.###hh.###hh",
  "aaaaaaaaaaaaa..eeiiiiiiiiiiiiiiiiiiiffffeeddhh..##hh..##hh..##hh",
  "aaaaaaaaaaaaaa..eeiiiiiiiiiiiiiiiiiiffeee.ddhhh..hhhh..hhhh..hhh",
  "ccccaaaaaaaacccc.eeiiiiiiiiiiiiiiiiieee...ddhhhhhhhhhhhhhhhhhhhh",
  "cccccaaaaaaacccc..eeiiiiiiiiiiiiiieee.....ddhhhhhhhhhhhhhhhhhhhh",
  "ccccccaaaaaacccca..eeiiiiiiiiiiieee.......ddhhh##hhhh##hhhh##hhh",
  "cccccccaaaaaccccaa..eeiiiiiiiieee.........ddhh.###hh.###hh.###hh",
  "ccccccccaaaaccccaaa..eeiiiiieee....a......ddhh..##hh..##hh..##hh",
  "cccccccccaaaccccaaaa..eeiieee....aaa..c...ddhhh..hhhh..hhhh..hhh",
  "ccccacccccaaccccaaaaa..eeee....aaaaa..c...ddhhhhhhhhhhhhhhhhhhhh",
  "ccccaacccccaccccaaccca.cec.cccaacccc..ccccddhhhhhhhhhhhhhhhhhhhh",
  "ccccaaacccccccccacaaacacc..aaacacaaac.c...cdhhh##hhhh##hhhh##hhh",
  "ccccaaaaccccccccacaaacac.aaccccacaaac.c...cdhh.###hh.###hh.###hh",
  "ccccaaaaacccccccacaaacacaacaaacacaaacacaaacdhh..##hh..##hh..##hh",
  "ccccaaaaaaccccccaaccccacaacaaacaccccaacaaacdhhh..hhhh..hhhh..hhh",
  "ccccaaaaaaacccccacaaacacaaaccccacaaaaacaaacdhhhhhhhhhhhhhhhhhhhh",
  "ccccaaaaaaaaccccaacccaaaaaaaaaaacaaaaaaaaaaahhhhhhhhhhhhhhhhhhhh"
};


/* XPM */
const gchar * Arc_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c None",
  "                    ",
  "                    ",
  "        .....       ",
  "      .........     ",
  "     ...+++++...    ",
  "    ..+++++++++..   ",
  "   ..+++++++++++..  ",
  "   ..+++++++++++..  ",
  "  ..+++++++++++++.. ",
  "  ..+++++++++++++.. ",
  "  ..+++++++++++++.. ",
  "  ..+++++++++++++.. ",
  "  ..+++++++++++++.. ",
  "   ..+++++++++++..  ",
  "   ..+++++++++++..  ",
  "    ..+++++++++..   ",
  "     ...+++++...    ",
  "      .........     ",
  "        .....       ",
  "                    "};
/* XPM */
const gchar * Axispoint_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "   .                ",
  "  ...               ",
  " .....              ",
  "   .                ",
  "   .                ",
  "  ... ....          ",
  "   .  .++....       ",
  "   .  .+++++.....   ",
  "  ... ..++++++++..  ",
  "   .   .++++++...   ",
  "   .   .+++++..     ",
  "  ...  ..+++++..    ",
  "   .    .++.+++..   ",
  "   .    .+...+++..  ",
  " .....  .+. ..+++.. ",
  "   .    ...  ..+++..",
  "   .     .    ..+.. ",
  "  ...          ...  ",
  "   .            .   "};
/* XPM */
const gchar * Axiswin_xpm[] = {
  "20 20 4 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "*	c #666666",
  "................... ",
  ".+++++++++++++++++.*",
  ".++++++.++++++++++.*",
  ".+++++...+++++++++.*",
  ".++++.....++++++++.*",
  ".++++++.++++++++++.*",
  ".++++++.++++++++++.*",
  ".+++++...+++++++++.*",
  ".++++++.++++++++++.*",
  ".++++++.++++++++++.*",
  ".+++++...+++++++++.*",
  ".++++++.+++++.++++.*",
  ".++++++.++.++..+++.*",
  ".+++............++.*",
  ".++++++.++.++..+++.*",
  ".++++++.+++++.++++.*",
  ".++++++.++++++++++.*",
  ".+++++++++++++++++.*",
  "...................*",
  " *******************"};
/* XPM */
const gchar * Clear_xpm[] = {
  "20 20 4 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "*	c #0099FF",
  "                    ",
  "          .....     ",
  "         .*.+++.    ",
  "        .*.*.+++.   ",
  "       .*.*.*.+++.  ",
  "      .*.*.*.*.+++. ",
  "     .*.*.*.*.*.+++.",
  "    .*.*.*.*.*.*....",
  "   .*.*.*.*.*.*.....",
  "  .*.*.*.*.*.*..... ",
  "  ..*.*.*.*.*.....  ",
  " .++.*.*.*.*.....   ",
  " .+++.*.*.*.....    ",
  " .++++.*.*.....     ",
  " .+++++.*.....      ",
  "  .+++++.....       ",
  "   .+++++++.        ",
  "    .+.+++.         ",
  "     .....          ",
  "                    "};
/* XPM */
const gchar * Coordwin_xpm[] = {
  "20 20 4 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "*	c #666666",
  "................... ",
  ".+++++++++++++++++.*",
  ".+++++++++++++++++.*",
  ".+++..++++++++++++.*",
  ".++....+++++++++++.*",
  ".++....+++++++++++.*",
  ".+++..++..++++++++.*",
  ".+++++++++..++++++.*",
  ".+++++++++++..++++.*",
  ".+++++++++++++..++.*",
  ".+++++++++++++++++.*",
  ".+++++++++++++++++.*",
  ".+++.+++.++.+++.++.*",
  ".++++.+.++++.+.+++.*",
  ".+++++.++++++.++++.*",
  ".++++.+.+++++.++++.*",
  ".+++.+++.++++.++++.*",
  ".+++++++++++++++++.*",
  "...................*",
  " *******************"};
/* XPM */
const gchar * Cross_xpm[] = {
  "20 20 2 1",
  " 	c None",
  ".	c #000000",
  "                    ",
  "                    ",
  "         .          ",
  "        ...         ",
  "       .....        ",
  "         .          ",
  "         .          ",
  "        ...         ",
  "         .          ",
  "         .          ",
  "        ...         ",
  "         .          ",
  "         .      .   ",
  "     .   .   .  ..  ",
  "  ................. ",
  "     .   .   .  ..  ",
  "     .   .      .   ",
  "         .          ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Curve_xpm[] = {
  "20 20 2 1",
  " 	c None",
  ".	c #000000",
  "                    ",
  "                    ",
  "    .....           ",
  "   ......           ",
  "  ...               ",
  "  ..                ",
  "  ..                ",
  "  ..                ",
  "  ..       .....    ",
  "  ...     .......   ",
  "   .........   ...  ",
  "    .......     ..  ",
  "                ..  ",
  "                ..  ",
  "                ..  ",
  "               ...  ",
  "           ......   ",
  "           .....    ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Datapoint_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "                    ",
  "   ..               ",
  "  ....              ",
  "  ....              ",
  "   ..               ",
  "      ....          ",
  "      .++....       ",
  "      .+++++.....   ",
  "      ..++++++++..  ",
  "       .++++++...   ",
  "       .+++++..     ",
  "       ..+++++..    ",
  "        .++.+++..   ",
  "        .+...+++..  ",
  "        .+. ..+++.. ",
  "        ...  ..+++..",
  "         .    ..+.. ",
  "               ...  ",
  "                .   "};
/* XPM */
const gchar * Draw_xpm[] = {
  "20 20 4 1",
  " 	c None",
  ".	c #000000",
  "+	c #00CCCC",
  "*	c #CC9900",
  "                    ",
  "           .        ",
  "          .+.       ",
  "         .+++.      ",
  "        .+++.+.     ",
  "       .+++.+.+.    ",
  "      .+++.+.+...   ",
  "     .+++.+.+.....  ",
  "    .+++.+.+.....   ",
  "   .+++.+.+.....    ",
  "  .+++.+.+.....     ",
  " .*.+.+.+.....      ",
  " .**.+.+.....       ",
  " .***.+.....        ",
  " .****.....         ",
  " .*****...          ",
  " ..*****.           ",
  " .......            ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Eval_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  " ........           ",
  " .++++++.           ",
  " ...++++.           ",
  " .++++++.           ",
  " ...++++.           ",
  " .++++++.           ",
  " ...++++.           ",
  " .++++++.  .......  ",
  " ....+++. ......... ",
  " .++++++. ..     .. ",
  " ...++++. ..     .. ",
  " .++++++.     ..... ",
  " ...++++.    .....  ",
  " .++++++.    ...    ",
  " ...++++.           ",
  " .++++++.    ...    ",
  " ........    ...    ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Fileopen_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "  ..                ",
  "  ......            ",
  "   .+++.            ",
  "   .+.......        ",
  "   .+.+++++.        ",
  "   .+.+.........    ",
  "   ...+.+++++++.    ",
  "     .+.+++++.......",
  "     .+.++++..+++++.",
  "     .+.+++...+.+.+.",
  "     ...++....+.+.+.",
  "       .+.....+++++.",
  "       .+.+.+.+.+.+.",
  "       .+.+.+.+.+.+.",
  "       ...+++++++++.",
  "         .+.+.+.+.+.",
  "         .+.+.+.+.+.",
  "         .+++++++++.",
  "         ..........."};
/* XPM */
const gchar * Filewin_xpm[] = {
  "20 20 4 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "*	c #666666",
  "................... ",
  ".+++++++++++++++++.*",
  ".++++.++++++++++++.*",
  ".++++.++++++++++++.*",
  ".++++.+++.+.+.+.++.*",
  ".++++.+++.+.+.+.++.*",
  ".+++++++++++++++++.*",
  ".+++..++++++++++++.*",
  ".+++++.+++++++++++.*",
  ".++++.+++.+.+.+.++.*",
  ".+++...++.+.+.+.++.*",
  ".+++++++++++++++++.*",
  ".+++..++++++++++++.*",
  ".+++++.+++++++++++.*",
  ".++++..++.+.+.+.++.*",
  ".+++++.++.+.+.+.++.*",
  ".+++..++++++++++++.*",
  ".+++++++++++++++++.*",
  "...................*",
  " *******************"};
/* XPM */
const gchar * Frame_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c None",
  "                    ",
  "                    ",
  "                    ",
  "   ...............  ",
  "   .+++.++.++.+++.  ",
  "   .++++++.++++++.  ",
  "   .+++++++++++++.  ",
  "   ..+++++++++++..  ",
  "   .+++++++++++++.  ",
  "   .+++++++++++++.  ",
  "   ...+++++++++...  ",
  "   .+++++++++++++.  ",
  "   .+++++++++++++.  ",
  "   ..+++++++++++..  ",
  "   .+++++++++++++.  ",
  "   .++++++.++++++.  ",
  "   .+++.++.++.+++.  ",
  "   ...............  ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Gauss_xpm[] = {
  "20 20 2 1",
  " 	c None",
  ".	c #000000",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "         ...        ",
  "        .   .       ",
  "       ..   ..      ",
  "       ..   ..      ",
  "       ..   ..      ",
  "      ..     ..     ",
  "      ..     ..     ",
  "      ..     ..     ",
  "      ..     ..     ",
  "     ..      ...    ",
  "     ..       ..    ",
  "  .....       ..... ",
  "  ....         .... ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Infowin_xpm[] = {
  "20 20 4 1",
  " 	c #FFFFFF",
  ".	c #0000CC",
  "+	c #FFFFFF",
  "*	c #000000",
  "********************",
  "*                  *",
  "*      ......      *",
  "*    ..........    *",
  "*   ....++++....   *",
  "*  .....++++.....  *",
  "*  ..............  *",
  "* .....+++++...... *",
  "* ......++++...... *",
  "* ......++++...... *",
  "* ......++++...... *",
  "* ......++++...... *",
  "* ......++++...... *",
  "*  .....++++.....  *",
  "*  ....++++++....  *",
  "*   ............   *",
  "*    ..........    *",
  "*      ......      *",
  "*                  *",
  "********************"};
/* XPM */
const gchar * Interrupt_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #CC0000",
  "+	c #FFFFFF",
  "                    ",
  "       ......       ",
  "     ..........     ",
  "    ............    ",
  "   ..............   ",
  "  ................  ",
  "  ................  ",
  " ..+++++++.++..++.. ",
  " .+....+..+..+.+.+. ",
  " ..++..+..+..+.+.+. ",
  " ....+.+..+..+.++.. ",
  " .+++..+...++..+... ",
  " .................. ",
  "  ................  ",
  "  ................  ",
  "   ..............   ",
  "    ............    ",
  "     ..........     ",
  "       ......       ",
  "                    "};
/* XPM */
const gchar * Legendpoint_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "  ..  ...   ..      ",
  " .  . .  . .  .     ",
  " .  . ...  .        ",
  " .... .  . .  .     ",
  " .  . ...   ..      ",
  "                    ",
  "      ....          ",
  "      .++....       ",
  "      .+++++.....   ",
  "      ..++++++++..  ",
  "       .++++++...   ",
  "       .+++++..     ",
  "       ..+++++..    ",
  "        .++.+++..   ",
  "        .+...+++..  ",
  "        .+. ..+++.. ",
  "        ...  ..+++..",
  "         .    ..+.. ",
  "               ...  ",
  "                .   "};
/* XPM */
const gchar * Legendwin_xpm[] = {
  "20 20 4 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "*	c #666666",
  "................... ",
  ".+++++++++++++++++.*",
  ".+++.+.+++++++++++.*",
  ".+++.+.+..++++++++.*",
  ".+++.+.+++.+++++++.*",
  ".++++++++++.++++++.*",
  ".+++++++++++.+++++.*",
  ".++++++++++++.+.++.*",
  ".++++.++++++++..++.*",
  ".+++...++++++...++.*",
  ".++++.++++++++++++.*",
  ".+++++.+++++++++++.*",
  ".+++++.+++++++++++.*",
  ".++++++.++++++++++.*",
  ".++++++.++++.+.+++.*",
  ".+++++++...+.+.+++.*",
  ".+++++++++++.+.+++.*",
  ".+++++++++++++++++.*",
  "...................*",
  " *******************"};
/* XPM */
const gchar * Line_xpm[] = {
  "20 20 2 1",
  " 	c None",
  ".	c #000000",
  "                    ",
  "                    ",
  "               .    ",
  "              ...   ",
  "             ...    ",
  "            ...     ",
  "           ...      ",
  "          ...       ",
  "         ...        ",
  "        ...         ",
  "       ...          ",
  "      ...           ",
  "     ...            ",
  "    ...             ",
  "   ...              ",
  "  ...............   ",
  "  ...............   ",
  "                    ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Load_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "...........         ",
  ".+++++++++.         ",
  ".+..++++++.         ",
  ".+++++++++.         ",
  ".+++++++++.         ",
  "...........         ",
  "                    ",
  "                    ",
  " ...         .......",
  " ...        ..+++++.",
  " ... ..    ...+.+.+.",
  " ... ..   ....+.+.+.",
  " ....... .....+++++.",
  " .........+.+.+.+.+.",
  "  ...... .+.+.+.+.+.",
  "     ..  .+++++++++.",
  "     .   .+.+.+.+.+.",
  "         .+.+.+.+.+.",
  "         .+++++++++.",
  "         ..........."};
/* XPM */
const gchar * Mark_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "                    ",
  "        .....       ",
  "      .........     ",
  "     ...++......    ",
  "    ..++++.......   ",
  "   ..+++++........  ",
  "   ..+++++........  ",
  "  ..++++++......... ",
  "  ..++++++......... ",
  "  ..++++++......... ",
  "  ..++++++......... ",
  "  ..++++++......... ",
  "   ..+++++........  ",
  "   ..+++++........  ",
  "    ..++++.......   ",
  "     ...++......    ",
  "      .........     ",
  "        .....       ",
  "                    "};
/* XPM */
const gchar * Math_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "  ...............   ",
  "  .+++++++++++++..  ",
  "  .+...........+..  ",
  "  .+.+.+.+.+.+.+..  ",
  "  .+.+.+.+.+.+.+..  ",
  "  .+...........+..  ",
  "  .+++++++++++++..  ",
  "  .+..+..+..+..+..  ",
  "  .+..+..+..+..+..  ",
  "  .+++++++++++++..  ",
  "  .+..+..+..+..+..  ",
  "  .+..+..+..+..+..  ",
  "  .+++++++++++++..  ",
  "  .+..+..+..+..+..  ",
  "  .+..+..+..+..+..  ",
  "  .+++++++++++++..  ",
  "  ................  ",
  "   ...............  ",
  "                    "};
/* XPM */
const gchar * Mergewin_xpm[] = {
  "20 20 4 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "*	c #666666",
  "................... ",
  ".+++++++++++++++++.*",
  ".+...............+.*",
  ".+..++.++.++.++..+.*",
  ".+..+++++++++++..+.*",
  ".+...+++++++++...+.*",
  ".+..+++++++++++..+.*",
  ".+..++.++.++.++..+.*",
  ".+...............+.*",
  ".+++++++++++++++++.*",
  ".+...............+.*",
  ".+..++.++.++.++..+.*",
  ".+..+++++++++++..+.*",
  ".+...+++++++++...+.*",
  ".+..+++++++++++..+.*",
  ".+..++.++.++.++..+.*",
  ".+...............+.*",
  ".+++++++++++++++++.*",
  "...................*",
  " *******************"};
/* XPM */
const gchar * Point_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "                    ",
  "  ...               ",
  "  .+....            ",
  "  ..+++....         ",
  "   .++++++....      ",
  "   .+++++++++..     ",
  "   ..++++++...      ",
  "    .++++++.        ",
  "    .++++++..       ",
  "    ..++++++..      ",
  "     .+...+++..     ",
  "     .+. ..+++..    ",
  "     ...  ..+++..   ",
  "      .    ..+++..  ",
  "            ..+++.. ",
  "             ..+..  ",
  "              ...   ",
  "               .    ",
  "                    "};
/* XPM */
const gchar * Polygon_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c None",
  "                    ",
  "                    ",
  "          .         ",
  "         ...        ",
  "        ..+..       ",
  "       ..+++..      ",
  "      ..+++++..     ",
  "     ..+++++++..    ",
  "    ..+++++++++..   ",
  "   ..+++++++++++..  ",
  "  ..+++++++++++++.. ",
  "   ..+++++++++++..  ",
  "    ..+++++++++..   ",
  "     ..+++++++..    ",
  "      ..+++++..     ",
  "       ..+++..      ",
  "        ..+..       ",
  "         ...        ",
  "          .         ",
  "                    "};
/* XPM */
const gchar * Preview_xpm[] = {
  "20 20 4 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "*	c #0000FF",
  "                    ",
  "  ................  ",
  "  .**************.  ",
  "  .********+*+*+*.  ",
  "  .**************.  ",
  "  .++++++++++++++.  ",
  "  .++++++++++++++.  ",
  "  .+++........+++.  ",
  "  .+++.++++++.+++.  ",
  "  .+++.++++++.+++.  ",
  "  .+++.++++++.+++.  ",
  "  .+++.++++++.+++.  ",
  "  .+++.++++++.+++.  ",
  "  .+++.++++++.+++.  ",
  "  .+++.++++++.+++.  ",
  "  .+++.++++++.+++.  ",
  "  .+++........+++.  ",
  "  .++++++++++++++.  ",
  "  ................  ",
  "                    "};
/* XPM */
const gchar * Print_xpm[] = {
  "20 20 6 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "*	c #CCCCCC",
  "#	c #999999",
  "R	c #FF9999",
  "                    ",
  "                    ",
  "        ............",
  "       .++++++++++. ",
  "      .++++++++++.  ",
  "     .++++++++++.   ",
  "     .++++++++++.   ",
  "    .++++++++++.    ",
  "    .++++++++++.....",
  "    .++++++++++...#.",
  "   ..++++++++++..##.",
  "  ..............###.",
  " ..............####.",
  " .************.####.",
  " .*RRR********.####.",
  " .************.###. ",
  " .*RRR********.##.  ",
  " .************.#.   ",
  " ...............    ",
  "                    "};
/* XPM */
const gchar * Rect_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "                    ",
  "                    ",
  "    .............   ",
  "    .............   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    ..+++++++++..   ",
  "    .............   ",
  "    .............   ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Save_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "...........         ",
  ".+++++++++.         ",
  ".+..++++++.         ",
  ".+++++++++.         ",
  ".+++++++++.         ",
  "...........         ",
  "                    ",
  "   .                ",
  "  ...        .......",
  " .....      ..+++++.",
  ".......    ...+.+.+.",
  "  ...     ....+.+.+.",
  "  ...    .....+++++.",
  "  ...    .+.+.+.+.+.",
  "  .....  .+.+.+.+.+.",
  "  .....  .+++++++++.",
  "   ....  .+.+.+.+.+.",
  "         .+.+.+.+.+.",
  "         .+++++++++.",
  "         ..........."};
/* XPM */
const gchar * Scale_xpm[] = {
  "20 20 2 1",
  " 	c None",
  ".	c #000000",
  "                    ",
  "    .               ",
  "   ...              ",
  "  .....  .......    ",
  "    .   .........   ",
  "    .   ..     ..   ",
  "    .   ..     ..   ",
  "    .       .....   ",
  "    .      .....    ",
  "    .      ...      ",
  "    .               ",
  "    .      ...      ",
  "    .      ...      ",
  "    .               ",
  "    .           .   ",
  "    .           ..  ",
  "  ................. ",
  "    .           ..  ",
  "    .           .   ",
  "                    "};
/* XPM */
const gchar * Scaleundo_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "=	c #0000CC",
  "                    ",
  ".  . .   . ...   .. ",
  ".  . ..  . .  . .  .",
  ".  . . . . .  . .  .",
  ".  . .  .. .  . .  .",
  " ..  .   . ...   .. ",
  "                    ",
  "       =            ",
  "      ==            ",
  "     ===            ",
  "    =============== ",
  "   ================ ",
  "  ================= ",
  " ================== ",
  "  ================= ",
  "   ================ ",
  "    =============== ",
  "     ===            ",
  "      ==            ",
  "       =            "};
/* XPM */
const gchar * Section_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "                    ",
  "  ................  ",
  "  .++.++.++.++.++.  ",
  "  .++.++.++.++.++.  ",
  "  ................  ",
  "  .++.++.++.++.++.  ",
  "  .++.++.++.++.++.  ",
  "  ................  ",
  "  .++.++.++.++.++.  ",
  "  .++.++.++.++.++.  ",
  "  ................  ",
  "  .++.++.++.++.++.  ",
  "  .++.++.++.++.++.  ",
  "  ................  ",
  "  .++.++.++.++.++.  ",
  "  .++.++.++.++.++.  ",
  "  ................  ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Single_xpm[] = {
  "20 20 2 1",
  " 	c None",
  ".	c #000000",
  "                    ",
  "                    ",
  "         .          ",
  "        ...         ",
  "       .....        ",
  "         .          ",
  "         .          ",
  "        ...         ",
  "         .          ",
  "         .          ",
  "        ...         ",
  "         .          ",
  "         .          ",
  "        ...         ",
  "         .          ",
  "         .          ",
  "        ...         ",
  "         .          ",
  "         .          ",
  "                    "};
/* XPM */
const gchar * Text_xpm[] = {
  "20 20 2 1",
  " 	c None",
  ".	c #000000",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "   ...............  ",
  "   ...   ...   ...  ",
  "   ..    ...    ..  ",
  "   ..    ...    ..  ",
  "         ...        ",
  "         ...        ",
  "         ...        ",
  "         ...        ",
  "         ...        ",
  "         ...        ",
  "         ...        ",
  "         ...        ",
  "      .........     ",
  "                    ",
  "                    ",
  "                    "};
/* XPM */
const gchar * Trimming_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "    .               ",
  "   ....  .          ",
  "  ..... .+.         ",
  "    .   .++.        ",
  "    .    .++.       ",
  "   ...   .+++.      ",
  "    .     .+++.     ",
  "   ..     .+++.     ",
  "  .++..    .++.     ",
  "   .+++..   .+.     ",
  "    .++++.  ..  ..  ",
  "   ...++++.......+. ",
  "    . .++++....++++.",
  "    .  .... ......+.",
  "   ...      .+.  ...",
  "    .      ..+.     ",
  "    .      .++..    ",
  "  .....     .++.    ",
  "    .        ...    "};
/* XPM */
const gchar * Zoom_xpm[] = {
  "20 20 3 1",
  " 	c None",
  ".	c #000000",
  "+	c #FFFFFF",
  "                    ",
  "         ......     ",
  "       ..........   ",
  "      ...++++++...  ",
  "      ..++++++++..  ",
  "     ..++++..++++.. ",
  "     ..++++..++++.. ",
  "     ..++......++.. ",
  "     ..++......++.. ",
  "     ..++++..++++.. ",
  "     ..++++..++++.. ",
  "     ...++++++++..  ",
  "    .....+++++....  ",
  "   ..............   ",
  "  ....+........     ",
  "  ...+..            ",
  "  ..+..             ",
  "   ...              ",
  "                    ",
  "                    "};

/* XPM */
const gchar * Move_xpm[] = {
"20 20 2 1",
" 	c None",
".	c #000000",
"                    ",
"                    ",
"                    ",
"         ..         ",
"        ....        ",
"       ......       ",
"         ..         ",
"     .   ..   .     ",
"    ..   ..   ..    ",
"   ..............   ",
"   ..............   ",
"    ..   ..   ..    ",
"     .   ..   .     ",
"         ..         ",
"       ......       ",
"        ....        ",
"         ..         ",
"                    ",
"                    ",
"                    "};
/* XPM */

const char * Axiswin48_xpm[] = {
"48 48 5 1",
" 	g None",
".	g #000000",
"+	g #FFFFFF",
"@	g #666666",
"#	g #333333",
"..............................................  ",
".++++++++++++++++++++++++++++++++++++++++++++.  ",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".+++++++++++.++++++++++++++++++++++++++++++++.@@",
".++++++++++...+++++++++++++++++++++++++++++++.@@",
".+++++++++.....++++++++++++++++++++++++++++++.@@",
".++++++++.......+++++++++++++++++++++++++++++.@@",
".+++++++...#.....++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++..#.....++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++..#.....++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++..#.....+++++++++++++++++++++.++++++.@@",
".++++++++++#.+++.+++++++.++++++.++++++..+++++.@@",
".++++++++++#.+++.+++++++.++++++.++++++...++++.@@",
".++++++++++#.+++.+++++++.++++++.++++++....+++.@@",
".++........#...............................++.@@",
".++###################################....+++.@@",
".++++++++++#.+++.+++++++.++++++.++++++...++++.@@",
".++++++++++#.+++.+++++++.++++++.++++++..+++++.@@",
".++++++++++#.+++++++++++++++++++++++++.++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++#.++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
"..............................................@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"};
/* XPM */

const char * Coordwin48_xpm[] = {
"48 48 121 2",
"  	g None",
". 	g #000000",
"+ 	g #FFFFFF",
"@ 	g #666666",
"# 	g #AEAEAE",
"$ 	g #707070",
"% 	g #3D3D3D",
"& 	g #5A5A5A",
"* 	g #8D8D8D",
"= 	g #E9E9E9",
"- 	g #323232",
"; 	g #0E0E0E",
"> 	g #020202",
", 	g #0B0B0B",
"' 	g #171717",
") 	g #7F7F7F",
"! 	g #3E3E3E",
"~ 	g #DBDBDB",
"{ 	g #CFCFCF",
"] 	g #292929",
"^ 	g #D8D8D8",
"/ 	g #5B5B5B",
"( 	g #E5E5E5",
"_ 	g #CDCDCD",
": 	g #FCFCFC",
"< 	g #DFDFDF",
"[ 	g #F3F3F3",
"} 	g #404040",
"| 	g #111111",
"1 	g #FDFDFD",
"2 	g #F2F2F2",
"3 	g #1C1C1C",
"4 	g #A3A3A3",
"5 	g #FEFEFE",
"6 	g #B5B5B5",
"7 	g #272727",
"8 	g #1E1E1E",
"9 	g #A9A9A9",
"0 	g #262626",
"a 	g #282828",
"b 	g #A1A1A1",
"c 	g #979797",
"d 	g #0D0D0D",
"e 	g #3A3A3A",
"f 	g #D5D5D5",
"g 	g #959595",
"h 	g #3F3F3F",
"i 	g #D4D4D4",
"j 	g #808080",
"k 	g #010101",
"l 	g #585858",
"m 	g #DADADA",
"n 	g #6D6D6D",
"o 	g #030303",
"p 	g #6C6C6C",
"q 	g #EFEFEF",
"r 	g #797979",
"s 	g #080808",
"t 	g #DCDCDC",
"u 	g #888888",
"v 	g #D2D2D2",
"w 	g #545454",
"x 	g #121212",
"y 	g #909090",
"z 	g #FBFBFB",
"A 	g #C8C8C8",
"B 	g #191919",
"C 	g #989898",
"D 	g #AFAFAF",
"E 	g #2B2B2B",
"F 	g #C0C0C0",
"G 	g #A8A8A8",
"H 	g #5E5E5E",
"I 	g #4A4A4A",
"J 	g #4D4D4D",
"K 	g #444444",
"L 	g #535353",
"M 	g #5D5D5D",
"N 	g #343434",
"O 	g #060606",
"P 	g #B8B8B8",
"Q 	g #9A9A9A",
"R 	g #E8E8E8",
"S 	g #252525",
"T 	g #8B8B8B",
"U 	g #8A8A8A",
"V 	g #787878",
"W 	g #FAFAFA",
"X 	g #E3E3E3",
"Y 	g #090909",
"Z 	g #070707",
"` 	g #CECECE",
" .	g #1A1A1A",
"..	g #8C8C8C",
"+.	g #494949",
"@.	g #4B4B4B",
"#.	g #414141",
"$.	g #919191",
"%.	g #A5A5A5",
"&.	g #040404",
"*.	g #0F0F0F",
"=.	g #E4E4E4",
"-.	g #999999",
";.	g #4E4E4E",
">.	g #9B9B9B",
",.	g #ECECEC",
"'.	g #EDEDED",
").	g #C9C9C9",
"!.	g #C1C1C1",
"~.	g #C2C2C2",
"{.	g #A2A2A2",
"].	g #383838",
"^.	g #E7E7E7",
"/.	g #838383",
"(.	g #505050",
"_.	g #949494",
":.	g #A6A6A6",
"<.	g #2E2E2E",
"[.	g #767676",
"}.	g #141414",
"|.	g #373737",
". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .     ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + .     ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + # $ % & * = + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + # - ; > , ' ) = + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + $ ; . . . . ! ~ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + % > . . . . , { + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + & , . . . . ] ^ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + * ' . . . . / ( + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + = ) ! , ] / _ : + < [ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + = ~ { ^ ( : + + } | * 1 + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + 2 % . . 3 4 5 + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + 6 7 . . 8 9 + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + 5 9 0 . . a b + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + 5 c d . . e f + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + : g ; . . h i + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + [ j d . k l m + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + 2 n o . > p q + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + [ r o . s ) q + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + t l > . ; u [ + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + v w . . x y z + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + A e . . B C z + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + D E . . F + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + G H + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + I . J + + + + K . L + + + + + + + M . N : + + + + : N . M + + + + + + . @ @ ",
". + + + + + + + + + m O . P + + Q . x R + + + + + + + [ S . T + + + + U . 0 [ + + + + + + . @ @ ",
". + + + + + + + + + + V . a W X ; . 4 + + + + + + + + + _ O Y t + + ~ Y Z ` + + + + + + + . @ @ ",
". + + + + + + + + + + [  .. ..+.. @.+ + + + + + + + + + + y . #.5 5 } . $.+ + + + + + + + . @ @ ",
". + + + + + + + + + + + %.. &.. *.=.+ + + + + + + + + + + + J . -.C . ;.+ + + + + + + + + . @ @ ",
". + + + + + + + + + + + + % . . >.+ + + + + + + + + + + + + ,.3 ; ; 3 '.+ + + + + + + + + . @ @ ",
". + + + + + + + + + + + + @.. . ).+ + + + + + + + + + + + + + !.. . ~.+ + + + + + + + + + . @ @ ",
". + + + + + + + + + + + {.. . . ].5 + + + + + + + + + + + + + + . . + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + ^.x . /.| . b + + + + + + + + + + + + + + . . + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + (.. h 5 _.. B 2 + + + + + + + + + + + + + . . + + + + + + + + + + + . @ @ ",
". + + + + + + + + + :.. Y ~ + : <.. [.+ + + + + + + + + + + + + . . + + + + + + + + + + + . @ @ ",
". + + + + + + + + = }.. * + + + F . O m + + + + + + + + + + + + . . + + + + + + + + + + + . @ @ ",
". + + + + + + + + w . |.1 + + + + l . I + + + + + + + + + + + + . . + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + . @ @ ",
". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . @ @ ",
"    @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"    @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ "};
/* XPM */

const char * Filewin48_xpm[] = {
"48 48 65 1",
" 	g None",
".	g #000000",
"+	g #FFFFFF",
"@	g #666666",
"#	g #F4F4F4",
"$	g #A3A3A3",
"%	g #010101",
"&	g #C3C3C3",
"*	g #8F8F8F",
"=	g #3F3F3F",
"-	g #7F7F7F",
";	g #DFDFDF",
">	g #BFBFBF",
",	g #CBCBCB",
"'	g #2C2C2C",
")	g #050505",
"!	g #2F2F2F",
"~	g #C8C8C8",
"{	g #333333",
"]	g #939393",
"^	g #F7F7F7",
"/	g #B2B2B2",
"(	g #242424",
"_	g #040404",
":	g #F8F8F8",
"<	g #E8E8E8",
"[	g #070707",
"}	g #DCDCDC",
"|	g #323232",
"1	g #686868",
"2	g #909090",
"3	g #0B0B0B",
"4	g #787878",
"5	g #FCFCFC",
"6	g #7D7D7D",
"7	g #B4B4B4",
"8	g #161616",
"9	g #2B2B2B",
"0	g #B7B7B7",
"a	g #262626",
"b	g #252525",
"c	g #AAAAAA",
"d	g #2A2A2A",
"e	g #EEEEEE",
"f	g #CFCFCF",
"g	g #0F0F0F",
"h	g #FEFEFE",
"i	g #EBEBEB",
"j	g #A1A1A1",
"k	g #4D4D4D",
"l	g #E4E4E4",
"m	g #1E1E1E",
"n	g #0D0D0D",
"o	g #BEBEBE",
"p	g #C6C6C6",
"q	g #171717",
"r	g #141414",
"s	g #3C3C3C",
"t	g #F1F1F1",
"u	g #BBBBBB",
"v	g #1A1A1A",
"w	g #AFAFAF",
"x	g #212121",
"y	g #030303",
"z	g #282828",
"..............................................  ",
".++++++++++++++++++++++++++++++++++++++++++++.  ",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".+++++#$%++++++++++++++++++++++++++++++++++++.@@",
".+++++...+++++&*&+++&*&+++&*&+++&*&++++++++++.@@",
".+++++++.+++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".+++++++.+++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".+++++++.+++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".+++++++.+++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".+++++++.+++++-.-+++-.-+++-.-+++-.-++++++++++.@@",
".+++++++++++++;>;+++;>;+++;>;+++;>;++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++,')!~+++++++++++++++++++++++++++++++++++.@@",
".++++{]^/(++++&*&+++&*&+++&*&+++&*&++++++++++.@@",
".++++_:+<[++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".++++++}|1++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".+++++2345++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".++++6)7++++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".++++8...9++++-.-+++-.-+++-.-+++-.-++++++++++.@@",
".+++++++++++++;>;+++;>;+++;>;+++;>;++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++0a)bc+++++++++++++++++++++++++++++++++++.@@",
".++++(defg++++&*&+++&*&+++&*&+++&*&++++++++++.@@",
".+++++hijk++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".+++++lmno++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".+++++++pq++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".++++rstuv++++=.=+++=.=+++=.=+++=.=++++++++++.@@",
".++++wxyzu++++-.-+++-.-+++-.-+++-.-++++++++++.@@",
".+++++++++++++;>;+++;>;+++;>;+++;>;++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
"..............................................@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"};
/* XPM */

const char * Infowin48_xpm[] = {
"48 48 5 1",
" 	c None",
".	c #000000",
"+	c #0000FF",
"@	c #666666",
"#	c #FFFFFF",
"..............................................  ",
".############################################.  ",
".############################################.@@",
".###################++++++###################.@@",
".###############++++++++++++++###############.@@",
".#############+++++++####+++++++#############.@@",
".###########++++++++######++++++++###########.@@",
".##########++++++++########++++++++##########.@@",
".#########+++++++++########+++++++++#########.@@",
".########++++++++++########++++++++++########.@@",
".#######+++++++++++########+++++++++++#######.@@",
".######+++++++++++++######+++++++++++++######.@@",
".#####+++++++++++++++####+++++++++++++++#####.@@",
".#####++++++++++++++++++++++++++++++++++#####.@@",
".####++++++++++++++++++++++++++++++++++++####.@@",
".####++++++++++++++++++++++++++++++++++++####.@@",
".###++++++++++++++++++++++++++++++++++++++###.@@",
".###++++++++++++###########+++++++++++++++###.@@",
".###++++++++++++###########+++++++++++++++###.@@",
".###+++++++++++++++########+++++++++++++++###.@@",
".##+++++++++++++++++#######++++++++++++++++##.@@",
".##+++++++++++++++++#######++++++++++++++++##.@@",
".##+++++++++++++++++#######++++++++++++++++##.@@",
".##+++++++++++++++++#######++++++++++++++++##.@@",
".##+++++++++++++++++#######++++++++++++++++##.@@",
".##+++++++++++++++++#######++++++++++++++++##.@@",
".###++++++++++++++++#######+++++++++++++++###.@@",
".###++++++++++++++++#######+++++++++++++++###.@@",
".###++++++++++++++++#######+++++++++++++++###.@@",
".###++++++++++++++++#######+++++++++++++++###.@@",
".####+++++++++++++++#######++++++++++++++####.@@",
".####+++++++++++++++#######++++++++++++++####.@@",
".#####++++++++++++++#######+++++++++++++#####.@@",
".#####++++++++++++++#######+++++++++++++#####.@@",
".######+++++++++++++#######++++++++++++######.@@",
".#######++++++++++++#######+++++++++++#######.@@",
".########++++++++++#########+++++++++########.@@",
".#########++++++##############++++++#########.@@",
".##########+++++##############+++++##########.@@",
".###########++++++++++++++++++++++###########.@@",
".#############++++++++++++++++++#############.@@",
".###############++++++++++++++###############.@@",
".###################++++++###################.@@",
".############################################.@@",
".############################################.@@",
"..............................................@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"};
/* XPM */

const char * Legendwin48_xpm[] = {
"48 48 42 1",
" 	g None",
".	g #000000",
"+	g #FFFFFF",
"@	g #666666",
"#	g #414141",
"$	g #0F0F0F",
"%	g #A2A2A2",
"&	g #9B9B9B",
"*	g #1D1D1D",
"=	g #FCFCFC",
"-	g #1F1F1F",
";	g #9E9E9E",
">	g #ACACAC",
",	g #FAFAFA",
"'	g #171717",
")	g #9F9F9F",
"!	g #B5B5B5",
"~	g #161616",
"{	g #1A1A1A",
"]	g #F8F8F8",
"^	g #131313",
"/	g #A4A4A4",
"(	g #C1C1C1",
"_	g #F7F7F7",
":	g #191919",
"<	g #898989",
"[	g #030303",
"}	g #4F4F4F",
"|	g #FEFEFE",
"1	g #151515",
"2	g #8F8F8F",
"3	g #434343",
"4	g #BEBEBE",
"5	g #BFBFBF",
"6	g #A5A5A5",
"7	g #656565",
"8	g #EBEBEB",
"9	g #323232",
"0	g #CFCFCF",
"a	g #404040",
"b	g #0E0E0E",
"c	g #0C0C0C",
"..............................................  ",
".++++++++++++++++++++++++++++++++++++++++++++.  ",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++.#++.#+++$$$$$$$$$$$$$$%++++++++++++++++++.@@",
".++.#++.#+++...............&+++++++++++++++++.@@",
".++.#++.#++++++++++++++++*..&++++++++++++++++.@@",
".++.#++.#++++++++++++++++=-..;+++++++++++++++.@@",
".++.#++.#+++++++++++++++++=*..>++++++++++++++.@@",
".++.#++.#++++++++++++++++++,'..)+++++++++++++.@@",
".++.#++.#+++++++++++++++++++=*..!++++++++++++.@@",
".++++++++++++++++++++++++++++,~..%+++++++++++.@@",
".+++++++++++++++++++++++++++++={..&++++++++++.@@",
".++++++++++++++++++++++++++++++]^../++++(_+++.@@",
".+++++++++++++++++++++++++++++++,:..)++<[}|++.@@",
".++++++++++++++++++++++++++++++++]1..23...4++.@@",
".+++++++++++++++++++++++++++++++++=-......5++.@@",
".++++++++++++++++++++++++++++++++++6......5++.@@",
".++++++++++++++++++++++++++++++++]7.......5++.@@",
".+++++++++++++++++++++++++++++++89........5++.@@",
".++0ab...c..4|+++++++++++++++++++.........5++.@@",
".++5.........+++++++++++++++++++|4..c...ba0++.@@",
".++5........98+++++++++++++++++++++++++++++++.@@",
".++5.......7]++++++++++++++++++++++++++++++++.@@",
".++5......6++++++++++++++++++++++++++++++++++.@@",
".++5......-=+++++++++++++++++++++++++++++++++.@@",
".++4...32..1]++++++++++++++++++++++++++++++++.@@",
".++|}[<++)..:,+++++++++++++++++++++++++++++++.@@",
".+++_(++++/..^]++++++++++++++++++++++++++++++.@@",
".++++++++++&..{=+++++++++++++++++++++++++++++.@@",
".+++++++++++%..~,++++++++++++++++++++++++++++.@@",
".++++++++++++!..*=+++++++++++++++++++#.++#.++.@@",
".+++++++++++++)..',++++++++++++++++++#.++#.++.@@",
".++++++++++++++>..*=+++++++++++++++++#.++#.++.@@",
".+++++++++++++++;..-=++++++++++++++++#.++#.++.@@",
".++++++++++++++++&..*++++++++++++++++#.++#.++.@@",
".+++++++++++++++++&...............+++#.++#.++.@@",
".++++++++++++++++++%$$$$$$$$$$$$$$+++#.++#.++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
"..............................................@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"};
/* XPM */

const char * Mergewin48_xpm[] = {
"48 48 4 1",
" 	g None",
".	g #000000",
"+	g #FFFFFF",
"@	g #666666",
"..............................................  ",
".++++++++++++++++++++++++++++++++++++++++++++.  ",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".+++......................................+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++....++++++++++++++++++++++++++++++....+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++....++++++++++++++++++++++++++++++....+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++......................................+++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".+++......................................+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++....++++++++++++++++++++++++++++++....+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++....++++++++++++++++++++++++++++++....+++.@@",
".+++.++++++++++++++++++++++++++++++++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++.+++++.+++++++.+++++++.+++++++.++++++.+++.@@",
".+++......................................+++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
".++++++++++++++++++++++++++++++++++++++++++++.@@",
"..............................................@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"};
