etc/ngraph-gtk/Ngraph.nsc
etc/ngraph-gtk/Ngraph.ngp
etc/ngraph-gtk/init.d/10append_addins.nsc
etc/ngraph-gtk/zsh/*
usr/bin
usr/share/icons
usr/share/ngraph-gtk/demo
icons/*.xpm usr/share/pixmaps
icons/*.png usr/share/pixmaps
misc/ngraph.applications usr/share/application-registry
misc/ngraph.desktop usr/share/applications
misc/ngraph.keys usr/share/mime-info
misc/ngraph.mime usr/share/mime-info
misc/ngraph.xml usr/share/mime/packages
