#ifndef _O_PARAMETER_HEADER
#define _O_PARAMETER_HEADER

#define OPARAMETER_WAIT_MIN 10
#define OPARAMETER_WAIT_MAX 1000

extern char *parameter_type[];

enum PARAMETER_TYPE {
  PARAMETER_TYPE_SPIN,
  PARAMETER_TYPE_SCALE,
  PARAMETER_TYPE_CHECK,
  PARAMETER_TYPE_SWITCH,
  PARAMETER_TYPE_COMBO,
  PARAMETER_TYPE_TRANSITION,
};

enum TRANSITION_INIT {
  TRANSITION_INIT_START,
  TRANSITION_INIT_STOP,
};

#endif
