#ifndef _O_PARAMETER_HEADER
#define _O_PARAMETER_HEADER

extern char *parameter_type[];

enum PARAMETER_TYPE {
  PARAMETER_TYPE_SPIN,
  PARAMETER_TYPE_SCALE,
  PARAMETER_TYPE_CHECK,
  PARAMETER_TYPE_COMBO,
  PARAMETER_TYPE_SWITCH,
};

#endif
