
  name: ngraph-gtk-htrb
  version: 'v6.08.01' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Ngraph is the program to create scientific 2-dimensional graphs for researchers and engineers. # 79 char long summary
  description: |
    Ngraph is the program to create scientific 2-dimensional graphs
    for researchers and engineers. Graphs can be exported to
    PostScript, SVG, PNG or PDF format.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    procs:
      source: https://github.com/htrb/ngraph-gtk/
      source-tag: *version
      plugin: nil

  apps:
    ngraph-gtk-htrb:
      command: ngraph-gtk