
  name: ngraph-gtk-htrb
  version: 'v6.08.01'
  summary: the program to create scientific 2-dimensional graphs.
  description: |
    Ngraph is the program to create scientific 2-dimensional graphs
    for researchers and engineers. Graphs can be exported to
    PostScript, SVG, PNG or PDF format.

  grade: devel # stable | devel
  confinement: strict

  parts:
    ngraph-gtk:
      plugin: [autotools, make, ruby]
