
  name: ngraph-gtk-htrb
  version: 'v6.08.01'
  summary: Ngraph is the program to create scientific 2-dimensional graphs for researchers and engineers.
  description: |
    Ngraph is the program to create scientific 2-dimensional graphs
    for researchers and engineers. Graphs can be exported to
    PostScript, SVG, PNG or PDF format.

  grade: stable
  confinement: strict

  parts:
    my-part:
      source: https://github.com/htrb/ngraph-gtk/
      source-tag: *version
      plugin: nil
