
name: ngraph-gtk-htrb
version: 'v6.08.02'
summary: the program to create scientific 2-dimensional graphs.
description: |
  Ngraph is the program to create scientific 2-dimensional graphs
  for researchers and engineers. Graphs can be exported to
  PostScript, SVG, PNG or PDF format.

grade: devel # stable | devel
confinement: strict
base: core18

apps:
  ngraph-gtk:
    command: ngraph
    extensions: [gnome-3-28]
    plugs:
      - gsettings # For desktop theme detection under Wayland session
      - home
    slots:
      - dbus-daemon
    common-id: com.github.htrb.ngraph-gtk.desktop
#    desktop: usr/share/applications/ngraph.desktop

parts:
  ngraph-gtk:
    source: https://github.com/htrb/ngraph-gtk.git
    source-branch: master
    plugin: autotools
    build-packages:
      - libgsl-dev
      - gettext
      - libreadline-dev
      - ruby-dev
      - libgtksourceview-3.0-dev
#    parse-info: [usr/share/metainfo/com.github.htrb.ngraph-gtk.appdata.xml]

  libraries:
    plugin: nil
    stage-packages:
      - libgsl23
      - ruby

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate
