
name: ngraph-gtk-htrb
version: 'v6.08.02'
summary: the program to create scientific 2-dimensional graphs.
description: |
  Ngraph is the program to create scientific 2-dimensional graphs
  for researchers and engineers. Graphs can be exported to
  PostScript, SVG, PNG or PDF format.

grade: stable # stable | devel
confinement: strict
base: core18

apps:
  ngraph-gtk:
    command: usr/bin/ngraph-snap.sh
    extensions: [gnome-3-28]
    plugs:
      - gsettings # For desktop theme detection under Wayland session
      - home
      - cups-control
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - removable-media
#    slots:
#      - dbus-daemon
    common-id: com.github.htrb.ngraph-gtk.desktop
    desktop: meta/gui/ngraph.desktop

parts:
  ngraph-gtk:
    source: https://github.com/htrb/ngraph-gtk.git
    source-branch: master
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
    override-build: |
       snapcraftctl build
       cp snap/local/ngraph-snap.sh $SNAPCRAFT_PART_INSTALL/usr/bin/
       mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui
       sed -i.bak -e 's|Icon=ngraph|Icon=${SNAP}/meta/gui/ngraph.png|g' -e 's|Exec=ngraph|Exec=ngraph-gtk-htrb.ngraph-gtk|g' misc/ngraph.desktop
       cp misc/ngraph.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
       cp osx/ngraph.iconset/icon_256x256.png $SNAPCRAFT_PART_INSTALL/meta/gui/ngraph.png
    build-packages:
      - libgsl-dev
      - gettext
      - libreadline-dev
      - ruby-dev
      - libgtksourceview-3.0-dev
    stage-packages:
      - ruby
      - xterm
      - aspell
      - aspell-en
      - raspell
#    parse-info: [usr/share/metainfo/com.github.htrb.ngraph-gtk.appdata.xml]

  libraries:
    plugin: nil
    stage-packages:
      - libgsl23
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libgtk-3-0
      - libgtksourceview-3.0-1
      - libharfbuzz0b
      - libicu60
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
#
# slots:
#   dbus-daemon:
#     interface: dbus
#     bus: session
#     name: com.github.htrb.ngraph-gtk
