name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Ubuntu Dependencies
      run: >
          sudo apt-get update -q && sudo apt-get install
          --no-install-recommends -y libgtk-3-dev libgsl-dev libreadline-dev ruby ruby-dev libgtksourceview-3.0-dev gettext
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
