name: C/C++ CI

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!gtk4'     # excludes gtk4
      - '!async-dialog'     # excludes async-dialog

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Ubuntu Dependencies
      run: >
          sudo apt-get update -q && sudo apt-get install
          --no-install-recommends -y libgtk-3-dev libgsl-dev libreadline-dev ruby ruby-dev libgtksourceview-4-dev gettext autopoint
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
